apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: usama1234567/todo-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb+srv://i222499:Usama123@cluster0.lrss2.mongodb.net/todo"
        - name: PORT
          value: "5000"
