name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Minikube Docker daemon
        run: eval $(minikube docker-env)

      - name: Build Backend Docker image
        run: |
          cd backend
          docker build -t usama1234567/todo-backend:latest .

      - name: Build Frontend Docker image
        run: |
          cd frontend
          docker build -t usama1234567/todo-frontend:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Backend Docker image
        run: docker push usama1234567/todo-backend:latest

      - name: Push Frontend Docker image
        run: docker push usama1234567/todo-frontend:latest

      - name: Deploy to Minikube
        run: kubectl apply -f k8s/

